apiVersion: apps/v1
kind: Deployment
metadata:
  name: oops-ai-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oops-ai-analyzer
  template:
    metadata:
      labels:
        app: oops-ai-analyzer
    spec:
      containers:
        - name: analyzer
          image: oops-ai/analyzer:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  selector:
    app: oops-ai-analyzer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000