apiVersion: apps/v1
kind: Deployment
metadata:
  name: ki-service
  namespace: oops-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ki-service
  template:
    metadata:
      labels:
        app: ki-service
    spec:
      containers:
        - name: ki-service
          image: oopsai/ki-service:latest  # Muss exakt mit dem gebauten Image-Namen übereinstimmen
          imagePullPolicy: Never  # Wichtig für lokale Images
          ports:
            - containerPort: 8000
          env:
            - name: OLLAMA_HOST
              value: "ollama:11434"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 45
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ki-service
  namespace: oops-ai
spec:
  selector:
    app: ki-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000